[package]
name = "quasar-ir"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "QUASAR quasar-ir"

[dependencies]
quasar-core = { path = "../quasar-core" }
