[package]
name = "quasar-algorithms"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "QUASAR quasar-algorithms"

[dependencies]
quasar-core = { path = "../quasar-core" }
