[package]
name = "quasar-runtime"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "QUASAR quasar-runtime"

[dependencies]
quasar-core = { path = "../quasar-core" }
